### PR TITLE
Improves reservoir to avoid a race condition and to be more fair

### PR DESCRIPTION
**Pull request by adriancole**
This re-uses the implementation we just made in Brave based on feedback
on yours. Enjoy!

See https://github.com/openzipkin/brave/pull/819

### CODE REVIEW

**Comment by adriancole** [comment]
sorry had a bug. should be ok now cc @abhiksingh

**Comment by adriancole** [comment]
build fail looks like a flake

**Comment by abhiksingh** [comment]
@adriancole thanks for the fix and a more fair reservoir implementation. The team is reviewing the code and we will look to merge this in at the earliest.

**Comment by haotianw465** [comment]
Hi @adriancole, I have created an issue for the flaky unit test. It is not related to this PR. The re-run build passed and I'm merging this in. Thank you for your contribution we really appreciate it.

**Pull request merged**
