### PR TITLE
Opt-in support to collect SQL queries.

### PR DESCRIPTION
**Pull request by stnor**
*Issue #, if available:*
https://github.com/aws/aws-xray-sdk-java/issues/28

*Description of changes:*
Opt-in to collect SQL via Environment or System property.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by stnor** [comment]
Is there support for displaying the SQL in the trace directly? Right now it's only available in SQL tab in the subsegment.
Screenshot 2021-05-01 at 21 39 33

**Review by willarmiros — COMMENTED** [review]
Sorry for missing the follow up on this, but code LGTM! Can you please include a blurb in the readme as well? https://github.com/aws/aws-xray-sdk-java#intercept-jdbc-based-sql-queries

**Comment by stnor** [comment]
Updated the readme, I hope it looks alright.

**Review by willarmiros — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
