### PR TITLE
GH-26 RetryingUDPEmitter

### PR DESCRIPTION
**Pull request by steven-aerts**
An emitter which will try to stream the entity when its send failed.

A possible implementation for step 2 of #26.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chrisradek** [comment]
@steven-aerts 
Thank you for submitting this pull request! I'll try to take a close look and respond to this over the next couple days. With the changes to the udp emitter we want to make sure it's completely backwards-compatible, and really appreciate the context you provided in #26

**Comment by luluzhao** [comment]
@steven-aerts thank you so much for contributing and sorry for the late response. I read your PR and I have a question about why you create another class `RetryingUDPEmitter`? Could you tell me more about it?

**Comment by steven-aerts** [comment]
Hi @luluzhao ,

My first preference was/is that the retry behaviour was the standard behaviour of the `UDPEmitter`.
But @haotianw465  [advised](https://github.com/aws/aws-xray-sdk-java/issues/26#issuecomment-420792901) against it.  So I created the subclass.  But I would prefer this is the defaullt behaviour.

**Comment by luluzhao** [comment]
@steven-aerts Travis CI tests are failing. Could you look into it and then fix it? Thank you.

**Comment by steven-aerts** [comment]
I agree that subsegment streaming seems a lot better.

Will reopen this PR (or a similar one) when we see the exception happen in this new code.

Thanks

**Pull request closed without merging**
